import Head from "next/head";
import Image from "next/image";
import { Nav } from "~/components/Nav";

import { api } from "~/utils/api";

import { Footer } from "~/components/Footer";


export default function Home() {
  const { data: sessions } = api.session.list.useQuery();

  return (
    <>
      <Head>
        <title>PB Tutoring</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" type="image/svg+xml" href="/public/favicon.svg" />
      </Head>
      <main className="bg-blue-800 min-h-screen relative flex flex-col gap-0 justify-between">
        <div>
          <Nav />
          <div className="flex flex-col xl:flex-row py-16 px-8 sm:p-16 xl:px-32 2xl:p-32 gap-16 sm:gap-24 xl:gap-32">
            <div className="flex-1 flex flex-col gap-6 2xl:gap-12">
              <h1 className="text-white font-bold text-2xl lg:text-5xl xl:text-6xl">Let&apos;s improve your test scores, together.</h1>
              <h2 className="text-white font-semibold text-md lg:text-lg">Work with current high school students who has achieved perfect ACT and PSAT scores as well as a student with a perfect AP Calculus AB score.</h2>
              <div className="bg-blue-900 p-6 sm:p-8 flex flex-col gap-4 rounded-xl">
                <p className="text-white font-semibold text italic text-xs lg:text-base">&quot;Jonah Pulliam and Sawyer Bivens have been some of my most dedicated and hard-working students. I am sure that they can help improve your mathematical abilities.&quot;</p>
                <div className="flex flex-col sm:flex-row gap-4 sm:items-center">
                  {/* <img src={TestimonyPFP} alt="&gt;" className="rounded-full w-12 h-12"></img> */}
                  <div className="flex flex-row gap-2 items-center">
                    <p className="text-white font-bold text-xs md:text-md">Bruce Maddox</p>
                    <p className="text-blue-100 font-semibold text-xs italic">AP Calculus Teacher</p>
                  </div>
                  <div className="flex flex-row gap-1 text-yellow-500 font-bold items-center text-xs sm:text-sm">
                    <Image src="/star.svg" alt="&gt;" height={12} width={12} className="h-3 sm:h-4" />
                    <Image src="/star.svg" alt="&gt;" height={12} width={12} className="h-3 sm:h-4" />
                    <Image src="/star.svg" alt="&gt;" height={12} width={12} className="h-3 sm:h-4" />
                    <Image src="/star.svg" alt="&gt;" height={12} width={12} className="h-3 sm:h-4" />
                    <Image src="/star.svg" alt="&gt;" height={12} width={12} className="h-3 sm:h-4" />
                    <span>(5.0)</span>
                  </div>
                </div>
              </div>
            </div>
            <hr className="border-blue-900 sm:hidden"/>
            <div className="flex-1 flex flex-col gap-8 sm:gap-4">
              {sessions?.filter(session => session.booked === false).slice(0, 5).map((session) => 
                <div className="bg-white w-full rounded-lg flex flex-col sm:flex-row" key={session.id}>
                  <div className="p-4 sm:px-8">
                    <p className="font-bold text-sm sm:text-base">{session.label}</p>
                    <div className="font-semibold text-[10px] flex flex-row gap-2">
                      <p className="flex flex-row items-center gap-1">
                        <Image width={10} height={10} alt="" src="/clock.svg" />
                        <span>{session.date} {session.time}</span>
                      </p>
                      <p className="flex flex-row items-center gap-1">
                        <Image width={10} height={10} alt="@" src="/map-pin.svg" />
                        <span>{session.location}</span>
                      </p>
                    </div>
                  </div>
                  <button className="sm:ml-auto justify-center sm:justify-normal text-xs 2xl:text-base px-2 2xl:px-4 md:px-8 py-3 sm:py-4 bg-red-600 font-semibold text-white flex flex-row items-center gap-2 rounded-b-lg sm:rounded-bl-none sm:rounded-r-lg hover:gap-4 duration-100 shadow-lg sm:shadow-none">
                    <span>Book Now</span>
                    <Image src="/chevron-right.svg" alt="&gt;" height={16} width={16} />
                  </button>
                </div>
              )}
              <p className="text-white font-semibold text-sm hover:underline cursor-pointer">See all planned sessions...</p>
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.post.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }
